server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8176
manager_ip: ${MANAGER_IP}
manager_port: ${MANAGER_PORT}
dc_sync_period: ${DC_SYNC_PERIOD}
resources_keep_alive_period: ${RESOURCES_KEEP_ALIVE_PERIOD}
